const BLP_MAGIC = 'BLP2';

const MAX_MIPS = 16;

enum BLP_COLOR_FORMAT {
  COLOR_JPEG = 0,
  COLOR_PAL,
  COLOR_DXT,
  NUM_COLOR_FORMATS,
}

enum BLP_PIXEL_FORMAT {
  PIXEL_DXT1 = 0,
  PIXEL_DXT3,
  PIXEL_ARGB8888,
  PIXEL_ARGB1555,
  PIXEL_ARGB4444,
  PIXEL_RGB565,
  PIXEL_A8,
  PIXEL_DXT5,
  PIXEL_UNSPECIFIED,
  PIXEL_ARGB2565,
  NUM_PIXEL_FORMATS,
}

enum BLP_IMAGE_FORMAT {
  IMAGE_UNSPECIFIED = 0,
  IMAGE_JPEG,
  IMAGE_RGBA8888,
  IMAGE_DXT1,
  IMAGE_DXT3,
  IMAGE_DXT5,
  NUM_IMAGE_FORMATS,
}

export { BLP_MAGIC, MAX_MIPS, BLP_COLOR_FORMAT, BLP_PIXEL_FORMAT, BLP_IMAGE_FORMAT };
